name: CD Pipeline - Deploy & Configure Network

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'ansible/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Clean up old containers (if any)
        run: |
          docker rm -f load_balancer backend-0 backend-1 2>/dev/null || true

      - name: Terraform Apply
        working-directory: terraform/docker
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Run Ansible Playbook
        working-directory: ansible
        run: ansible-playbook configure.yml